version: 2
updates:
  # npm dependencies
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Sao_Paulo
    labels:
      - dependencies
      - automerge
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - ci-cd
      - automerge

  # Docker
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Sao_Paulo
    labels:
      - docker
      - automerge
